src/Entity/Product.php
<?php

namespace App\Entity;

use App\Repository\ProductRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=ProductRepository::class)
 */
class Product
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     * @Assert\NotBlank(message="Le nom du produit ne peut pas être vide.")
     * @Assert\Length(max=50, maxMessage="Le nom du produit doit faire {{limit}} caractères maximum.")
     */
    private $name;

    /**
     * @ORM\Column(type="float")
     * @Assert\Positive(message="Le prix doit être positif.")
     */
    private $price;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_highlighted = false;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $image;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Positive(message="Le prix doit être positif.")
     */
    private $XS;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Positive(message="Le prix doit être positif.")
     */
    private $S;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Positive(message="Le prix doit être positif.")
     */
    private $M;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Positive(message="Le prix doit être positif.")
     */
    private $L;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Positive(message="Le prix doit être positif.")
     */
    private $XL;

    #/**
    # * @ORM\OneToMany(targetEntity=StockSize::class, mappedBy="product", orphanRemoval: true, cascade:['persist'] )
    # */
    #private $stockSizes;

    #public function __construct()
    #{
    #    $this->stockSizes = new ArrayCollection();
    #}

    #/**
    # * @ORM\OneToMany(targetEntity=Stock::class, mappedBy="product", orphanRemoval=true)
    # */
    #private $stocks;

    #public function __construct()
    #{
    #    $this->stocks = new ArrayCollection();
    #}

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getFormattedPrice(): string
    {
        return number_format($this->price,2,',',' ');
    }

    public function isHighlighted(): ?bool
    {
        return $this->is_highlighted;
    }

    public function setIsHighlighted(bool $is_highlighted): self
    {
        $this->is_highlighted = $is_highlighted;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }

    #/**
    # * @return Collection<int, Stock>
    # */
    #public function getStocks(): Collection
    #{
    #    return $this->stocks;
    #}

    #public function addStock(Stock $stock): self
    #{
    #    if (!$this->stocks->contains($stock)) {
    #        $this->stocks[] = $stock;
    #        $stock->setProduct($this);
    #    }
    #
    #    return $this;
    #}

    #public function removeStock(Stock $stock): self
    #{
    #    if ($this->stocks->removeElement($stock)) {
    #        // set the owning side to null (unless already changed)
    #        if ($stock->getProduct() === $this) {
    #            $stock->setProduct(null);
    #        }
    #    }

    #    return $this;
    #}

    #/**
    # * @return Collection<int, StockSize>
    # */
    #public function getStockSizes(): Collection
    #{
    #    return $this->stockSizes;
    #}

    #public function addStockSize(StockSize $stockSize): self
    #{
    #    if (!$this->stockSizes->contains($stockSize)) {
    #        $this->stockSizes[] = $stockSize;
    #        $stockSize->setProduct($this);
    #    }

    #    return $this;
    #}

    #public function removeStockSize(StockSize $stockSize): self
    #{
    #    if ($this->stockSizes->removeElement($stockSize)) {
    #        // set the owning side to null (unless already changed)
    #        if ($stockSize->getProduct() === $this) {
    #            $stockSize->setProduct(null);
    #        }
    #    }

    #    return $this;
    #}

    public function getXS(): ?int
    {
        return $this->XS;
    }

    public function setXS(int $XS): self
    {
        $this->XS = $XS;

        return $this;
    }

    public function getS(): ?int
    {
        return $this->S;
    }

    public function setS(int $S): self
    {
        $this->S = $S;

        return $this;
    }

    public function getM(): ?int
    {
        return $this->M;
    }

    public function setM(int $M): self
    {
        $this->M = $M;

        return $this;
    }

    public function getL(): ?int
    {
        return $this->L;
    }

    public function setL(int $L): self
    {
        $this->L = $L;

        return $this;
    }

    public function getXL(): ?int
    {
        return $this->XL;
    }

    public function setXL(int $XL): self
    {
        $this->XL = $XL;

        return $this;
    }
}

src/Controller/CartController.php
<?php

namespace App\Controller;
use App\Entity\Product;


use App\Repository\ProductRepository;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Stripe\Checkout\Session;
use Stripe\Stripe;
use Symfony\Component\HttpFoundation\Request;
use App\Service\StripeService;

/**
* @Route("/cart", name="app_cart_")
*/
class CartController extends AbstractController
{
    /**
     * @Route("/", name="cart")
     */
    public function index(SessionInterface $session,ProductRepository $productRepository): Response
    {
        $this->denyAccessUnlessGranted('ROLE_USER');

        $panier = $session->get("panier",[]);
    
        
        //on "fabrique" les données
        $contenuPanier = [];
        $total = 0;
        

        foreach($panier as $productSize=> $quantity){
            //dd(strtok($productSize,"."));
            $id = strtok($productSize,".");
            $product = $productRepository->find($id);
            $xxx=explode(".",$productSize);
            
            $size = ($xxx[1]);
            $contenuPanier[] = [
                "orderedProduct" => $product,
                "orderedQuantity" => $quantity,
                "size" => $size,
            ];
            
            $total += $product->getPrice() * $quantity;
        }
        
      

        return $this->render('cart/cart.html.twig', [
            'controller_name' => 'CartController',
            'contenuPanier' => $contenuPanier,
            'total' => $total,
        ]);
    }

    /**
     * @Route("/add/{id}/{size?}", name="add", defaults={"size": ""})
     */
    public function add($id,$size, SessionInterface $session, ProductRepository $productRepository): Response
    {
        $this->denyAccessUnlessGranted('ROLE_USER');
        
        //on récupère le panier actuel
        $panier = $session->get("panier",[]);
        $id = $productRepository->findOneBy(['id'=>$id])->getId();
        $productSize = $id.".".$size;
        
        
        if(isset($panier[$productSize])){
            $panier[$productSize]++; 
        }
        else{
            $panier[$productSize] =1;
        }
      

        //on sauvegarde la session
        $session -> set("panier", $panier);
        //dd($session);

        return $this->redirectToRoute("app_cart_cart");
    }

    /**
     * @Route("/remove/{id}/{size?}", name="remove")
     */
    public function remove($id,$size, SessionInterface $session, ProductRepository $productRepository): Response
    {
        $this->denyAccessUnlessGranted('ROLE_USER');

        //on récupère le panier actuel
        $panier = $session->get("panier",[]);
        $id = $productRepository->findOneBy(['id'=>$id])->getId();
        $productSize = $id.".".$size;
        
       // $id = $product->getId();

        if(!empty($panier[$productSize])){
            if($panier[$productSize]>1){
                $panier[$productSize]--;
            }
            else {
                unset($panier[$productSize]);
            }
            
        }
        

        //on sauvegarde la session
        $session -> set("panier", $panier);
      

        return $this->redirectToRoute("app_cart_cart");
    }

    /**
     * @Route("/pay", name="pay")
     */
    public function pay(SessionInterface $session, ProductRepository $productRepository, StripeService $stripeService): Response
    {
        $this->denyAccessUnlessGranted('ROLE_USER');
        $panier = $session->get("panier",[]);
        $panierId = $session->getId();

        $contenuPanier = [];
        
        foreach($panier as $productSize=> $quantity){
            
            $id = strtok($productSize,".");
            $product = $productRepository->find($id);
            $xxx=explode(".",$productSize);
            
            $size = ($xxx[1]);
            $contenuPanier[] = [
                "orderedProduct" => $product,
                "orderedQuantity" => $quantity,
                "size" => $size,
            ];
           
            
        }
        

        $checkout_session = $stripeService->stripe($contenuPanier,$panierId);
      
        //dd($checkout_session);
        //////////////////////////////////////////////////////////////////
        return $this->redirect($checkout_session);
        
       
    }

    /**
     * @Route("/pay/success", name="pay_success")
     */
    public function success(Request $request,SessionInterface $session): Response
    {
       
        //on récupère le panier pour le supprimer
        $session->set("panier",[]);
          
        return $this->render('cart/success.html.twig', [
            'controller_name' => 'CartController',
            
        ]);
    }

    /**
     * @Route("/pay/cancel", name="pay_cancel")
     */
    public function cancel(): Response
    {
        return $this->render('cart/cancel.html.twig', [
            'controller_name' => 'CartController',
            
        ]);
    }

}

templates/cart/cancel.html.twig
{% extends 'base.html.twig' %}

{% block title %}Achat annulé{% endblock %}

{% block body %}
<main>
    <section class="container text-center">
        <h1>Votre paiement est annulé</h1>
        <p>Merci de votre confiance</p>
        <p>Votre panier sera conservé pendant 24h.</p>
        <a href="{{path('app_products')}}" class="btn" style="width: 200px;border:solid #556B2F 1px;background-color:#8FBC8F;">Retour sur la boutique</a>

    </section>
    
</main>
{% endblock %}

templates/cart/cart.html.twig
{% extends 'base.html.twig' %}

{% block title %}Votre panier{% endblock %}

{% block body %}
<main>
    <section class="container">
    {% for article in contenuPanier %}
    <div class="mx-auto p-2" style="width: 90%;border:solid black 1px;margin-top:50px; margin-bottom:30px;">

            <div  class="row">
                <div class="col-md-3"><img src="{{ asset('uploads/' ~ article.orderedProduct.image) }}" alt="{{ article.orderedProduct.name }}">
                </div>
                <div class="col-md-2" style="align-content: center;">
                <label>Nom:</label>
                <div style="border:solid black 1px;text-align:center;">{{ article.orderedProduct.name }}</div>
                </div>
                <div class="col-md-2" style="align-content: center;">
                <label>Prix:</label>
                <div style="border:solid black 1px;text-align:center;">{{article.orderedProduct.formattedPrice}}€</div>
                </div>
                <div class="col-md-2" style="align-content: center;">
                <label>Taille :</label>
                <div style="border:solid black 1px;text-align:center;">{{article.size}}</div>
                </div>
                <div class="col-md-2" style="align-content: center;">
                <label>Quantité :</label>
                <div style="border:solid black 1px;text-align:center;">{{article.orderedQuantity}}</div>
                </div>

                <div class="text-end">
                    <a href="{{path('app_cart_remove', {id:article.orderedProduct.id,size:article.size})}}" class="btn" style="width: 200px;border:solid black 1px;">Retirer du panier</a>
                </div>
            </div>
            
    </div>
    
    {% else %}
    <p class="text-center">Votre panier est vide</p>
    {% endfor %}
    <div class="row mx-auto p-2" style="width: 90%;justify-content:flex-end">
        <div  class="col col-md-3">
            <div style="width: 200px;border:solid black 1px;" class="text-center col-md-3">TOTAL : {{total|number_format(2, ',', ' ')}}€</div>
            
        </div>
        <div  class="col col-md-3">
            <div class="row">
            <a href="{{path('app_cart_pay')}}" class="btn" style="width: 200px;border:solid #DC143C 1px; background-color:#F08080;margin-bottom:10px;" class="col-md-3">Finaliser la commande</a>
            <a href="{{path('app_products')}}" class="btn" style="width: 200px;border:solid #556B2F 1px;background-color:#8FBC8F;">Continuer mes achats</a>
            </div>
        </div>
    </div>
    
    </section>
    
</main>
{% endblock %}

templates/cart/success.html.twig
{% extends 'base.html.twig' %}

{% block title %}Achat confirmé{% endblock %}

{% block body %}
<main>
    <section class="container text-center">
        <h1>Achat réalisé avec succès!</h1>
        <p>Merci de votre confiance</p>
        <a href="{{path('app_products')}}" class="btn" style="width: 200px;border:solid #556B2F 1px;background-color:#8FBC8F;">Retour sur la boutique</a>

    </section>
    
</main>
{% endblock %}